baseURL = "https://hotel-website-demo.pages.dev/"
languageCode = "en-us"
title = "La Quinta Inn & Suites by Wyndham Cincinnati NE - Mason"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
  description = "La Quinta Inn & Suites by Wyndham Cincinnati NE - Mason is a Mason, Ohio hotel near Kings Island with complimentary breakfast, free Wi-Fi, free parking, an indoor pool, and hot tub."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"
